"""Byte-level ASS roundtrip fidelity tests.

Covers three known pysubs2 serialization losses Phase 1 did not catch:

1. UTF-8 BOM is stripped by reader and never re-added on write.
2. CRLF line terminators become LF (pysubs2 always emits ``\\n``).
3. Style floats that happen to be whole numbers lose their trailing ``.0``
   (pysubs2 formats ``100.0`` as ``"100"``).

The test uses a YYeTs-style fixture that exercises all three faults in a
single file. The fixture is generated inline so tests remain self-contained.
"""

from __future__ import annotations

from pathlib import Path

from lattifai.caption import Caption


# Minimal reproduction of the YYeTs sample: UTF-8 BOM + CRLF throughout +
# ScaleX/ScaleY/Spacing/Angle/Outline/Shadow written as ``100.0`` / ``0.0``.
YYETS_STYLE_ASS_UTF8_BOM_CRLF = (
    "\ufeff"  # BOM
    "[Script Info]\r\n"
    "; Script generated by Arctime Pro 4.3\r\n"
    "ScriptType: v4.00+\r\n"
    "WrapStyle: 2\r\n"
    "PlayResX: 1920\r\n"
    "PlayResY: 816\r\n"
    "ScaledBorderAndShadow: yes\r\n"
    "YCbCr Matrix: None\r\n"
    "\r\n"
    "[V4+ Styles]\r\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\r\n"
    "Style: Default,微软雅黑,54,&H00FFFFFF,&H00FFFFFF,&H19533B3B,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,3.1,1.2,2,135,135,72,1\r\n"
    "Style: 中文 1080,微软雅黑,75,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,2.0,2.0,2,10,10,90,1\r\n"
    "\r\n"
    "[Events]\r\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n"
    "Dialogue: 2,0:00:24.07,0:01:11.95,中文 1080,atg1,0,0,0,,{\\fad(120,120)}测试中文字幕\r\n"
    "Dialogue: 1,0:00:24.07,0:01:08.75,Default,atg1,0,0,0,,{\\fad(120,120)}Test English subtitle\r\n"
)


def test_utf8_bom_preserved_on_roundtrip(tmp_path: Path) -> None:
    """UTF-8 BOM from input must appear at the start of write output."""
    inp = tmp_path / "in.ass"
    inp.write_bytes(YYETS_STYLE_ASS_UTF8_BOM_CRLF.encode("utf-8"))

    cap = Caption.read(str(inp))
    assert cap.metadata.get("encoding") == "utf-8-sig"

    out_path = tmp_path / "out.ass"
    cap.write(str(out_path))
    out_bytes = out_path.read_bytes()

    assert out_bytes[:3] == b"\xef\xbb\xbf", (
        f"UTF-8 BOM lost on write; first 6 bytes: {out_bytes[:6]!r}"
    )


def test_crlf_line_terminators_preserved(tmp_path: Path) -> None:
    """CRLF input must round-trip as CRLF output (no bare LF)."""
    inp = tmp_path / "in.ass"
    inp.write_bytes(YYETS_STYLE_ASS_UTF8_BOM_CRLF.encode("utf-8"))

    cap = Caption.read(str(inp))
    assert cap.metadata.get("line_terminator") == "\r\n"

    out_path = tmp_path / "out.ass"
    cap.write(str(out_path))
    data = out_path.read_bytes()

    # Count bare LF (LF not preceded by CR). Must be zero for a pure-CRLF file.
    import re

    bare_lf_count = len(re.findall(rb"(?<!\r)\n", data))
    crlf_count = data.count(b"\r\n")
    assert bare_lf_count == 0, (
        f"Found {bare_lf_count} bare LF (expected 0); "
        f"CRLF count: {crlf_count}"
    )


def test_style_float_format_preserved(tmp_path: Path) -> None:
    """Style floats that were ``100.0`` / ``0.0`` / ``2.0`` stay with ``.0``."""
    inp = tmp_path / "in.ass"
    inp.write_bytes(YYETS_STYLE_ASS_UTF8_BOM_CRLF.encode("utf-8"))

    cap = Caption.read(str(inp))
    out_path = tmp_path / "out.ass"
    cap.write(str(out_path))

    text = out_path.read_text(encoding="utf-8-sig")
    style_lines = [ln for ln in text.splitlines() if ln.startswith("Style:")]
    assert style_lines, "no Style lines found in output"

    # Default style line from fixture: ScaleX=100.0, Spacing=0.0, Outline=3.1
    default_line = next((ln for ln in style_lines if ln.startswith("Style: Default,")), None)
    assert default_line is not None

    # pysubs2 alone would emit "100,100,0,0" -- these must be restored to "100.0,100.0,0.0,0.0"
    assert "100.0,100.0,0.0,0.0" in default_line, (
        f"Style float format not preserved. Got: {default_line}"
    )
    assert "3.1,1.2" in default_line  # non-whole values were never broken


def test_full_byte_diff_excluding_dialogue(tmp_path: Path) -> None:
    """Everything except Dialogue lines (which may be reflowed) is byte-identical.

    This is the end-to-end roundtrip guarantee: a YYeTs-style file with no
    supervisions mutated yields an output byte-for-byte equal to the input
    in the [Script Info], [V4+ Styles], [Events] Format header regions.
    """
    inp = tmp_path / "in.ass"
    inp.write_bytes(YYETS_STYLE_ASS_UTF8_BOM_CRLF.encode("utf-8"))

    cap = Caption.read(str(inp))
    out_path = tmp_path / "out.ass"
    cap.write(str(out_path))

    in_text = inp.read_text(encoding="utf-8-sig")
    out_text = out_path.read_text(encoding="utf-8-sig")

    # Extract everything up to (but not including) the first Dialogue: line.
    def header_region(text: str) -> str:
        lines = text.split("\r\n") if "\r\n" in text else text.split("\n")
        out = []
        for ln in lines:
            if ln.startswith("Dialogue:"):
                break
            out.append(ln)
        return "\n".join(out)  # normalize line ending for the comparison only

    assert header_region(in_text) == header_region(out_text), (
        "Header region (Script Info + Styles + Events Format) diverged; "
        "full roundtrip not preserved"
    )
